version: "3"

services:
  frontend:
    build:
      context: ./client  # Ensure this is indented properly under build
    container_name: client
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - react-express
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for chokidar
      - WATCHPACK_POLLING=true    # Enable polling for watchpack

  backend:
    build:
      context: ./server  # Ensure this is indented properly under build
    container_name: server
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for chokidar
      - WATCHPACK_POLLING=true    # Enable polling for watchpack

  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - mongo-data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

networks:
  react-express:
  express-mongo:

volumes:
  mongo-data:
